### ISSUE TITLE
*P1* - "Main Page Header"

### ISSUE THREAD

**Issue by Mtduffey36** [Mtduffey36/hair-and-co#1]
Acceptance Criteria:

GIVEN "When I load the page"
THEN "I see a header with a nav-bar"

GIVEN "When I look at the nav-bar"
THEN "I see a logo for the salon"
GIVEN "When I look at the nav-bar"
THEN "I see links for "Home, About Us, Contact, Services, Book Appointment"

GIVEN "When I look at the nav-bar"
THEN "I see a sign-in and register button"

**Comment by Ejacosta86** [comment]
processed with Andres
 nav-bar"
logo for the salon"
links for "Home, About Us, Contact, Services, Book Appointment"
