### ISSUE TITLE
*P1* - "Main Page Footer"

### ISSUE THREAD

**Issue by Mtduffey36** [Mtduffey36/hair-and-co#3]
Acceptance Criteria:

GIVEN "When I look at the main page"
THEN "I see a footer with social media links"

GIVEN "When I look at the links"
THEN "I see a link for facebook: https://www.facebook.com/haircopearl/"
THEN "I see a link for instagram: https://www.instagram.com/hairandcompanysalon/"

**Comment by Ejacosta86** [comment]
processed with Andres

created links to facebook and instagram
